### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by MOONCHAND** [PayelGanguly96/Loan-Prediction#1]
I am getting an error called NameError.How to fix this.Please reply as soon as possible.
![Screenshot (122)](https://user-images.githubusercontent.com/39911581/56880953-5ec57a80-6a7c-11e9-9795-1539e8c208be.png)

**Comment by Shrirang97** [comment]
fig.plot(kind='bar')

**Comment by MOONCHAND** [comment]
No this is not working again getting an AttributeError.

**Comment by Shrirang97** [comment]
ch.plot(kind='bar')
ch and pt must be dataframe because they have method having attribute kind
see the link below
[https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.plot.html](url)

**Comment by MOONCHAND** [comment]
In dataframe where is ch and pt data.I have taken your data set there's nothing ch and pt in dataframe then how do I access them please help me.

**Comment by MOONCHAND** [comment]
pt is there but ch is'nt.

**Comment by MOONCHAND** [comment]
![Screenshot (123)](https://user-images.githubusercontent.com/39911581/56889712-c7205600-6a94-11e9-9aff-f312696779cb.png)
What is there before 'le'

**Comment by Shrirang97** [comment]
ch = df['Credit_History'].value_counts(ascending=True)
ch.head()
see cell no 60




What is there before 'le'?
what exactly error is ?? explain.

**Comment by MOONCHAND** [comment]
![Screenshot (124)](https://user-images.githubusercontent.com/39911581/56890077-0b602600-6a96-11e9-86b3-b9b781e93d1f.png)
Here it is.

**Comment by Shrirang97** [comment]
https://stackoverflow.com/questions/46406720/labelencoder-typeerror-not-supported-between-instances-of-float-and-str/46406995

df[i] = le.fit_transform(df[i].astype(str))

**If you found any error, copy and paste it on google. You will always find answer. On stackoverflow such errors are already solved.**

**Comment by MOONCHAND** [comment]
Thanks bro!
I got it, actually I am new in machine learning that's why facing so many errors and problems as well as disturbed you.But never mind it bro.

**Comment by Shrirang97** [comment]
I will always be happy to help bro. 

ML is a subject where you have to explore things. It's fun to solve errors. 

If you have any error and can't find on google, let me know.

#CoderLife😀

**Comment by MOONCHAND** [comment]
If you insist me then I will happily try to ask.
